name: Flight Price Monitor

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  search-flights:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Run flight search
      env:
        AMADEUS_API_KEY: ${{ secrets.AMADEUS_API_KEY }}
        AMADEUS_API_SECRET: ${{ secrets.AMADEUS_API_SECRET }}
      run: |
        python amadeus_flight_search.py
      continue-on-error: true
    
    - name: Commit results
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
        git add -A
        
        # 檢查係咪有改動
        if git diff --staged --quiet; then
          echo "✓ 冇新數據需要 commit"
          exit 0
        fi
        
        # 有改動就 commit 同 push
        git commit -m "Update flight data - $(date +'%Y-%m-%d %H:%M:%S')"
        git push
